### ISSUE TITLE
動的ページの生成

### ISSUE THREAD

**Issue by szk18** [slide-share-spot/slide-share-spot#12]
検索結果に表示される各論文に個別のページを生成したい。
`_slug.vue` を用意してよしなにすれば実現可能？

参考
https://qiita.com/yuki21/items/87d5bb8696b3dc712c0d

**Comment by marie-prog0627** [comment]
ページ表示の際に，idを渡して，そこからfirestoreにデータを取りに行って，そのデータを1つのページに流し込めばええんちゃう？

**Comment by szk18** [comment]
たぶんそれで良さそう！

**Comment by marie-prog0627** [comment]
解決！できた！
